spring.application.name=foodapi

# Mongo DB Configurations
spring.data.mongodb.uri=${MONGO_URL}

# AWS S3 Bucket Configurations
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region = ap-south-1
aws.s3.bucketname = milkies-milk

#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}


jwt.secret.key = "$brundhavan777#milkdairy!3kilari"